import { ProductFormValues } from "@/components/organisms/product/AddProductForm";

export const sampleProducts: ProductFormValues[] = [
  {
    productCategoryId: "1",
    productName: "Electric Kettle - 1.8L",
    productDescription:
      "Boils water fast with auto shut-off and stainless steel body.",
    productBrand: "HomeSmart",
    stockKeepingUnit: "HSK-1800",
    productModelNumber: "KTL-HS-1800",
    productBestSaleTag: "Best Seller",
    productDiscountPercentage: 20,
    productPrice: 1599,
    productDiscountPrice: 1279,
    saleDayleft: 15,
    availableStockQuantity: 120,
    productWeight: 0.9,
    productSizes: "",
    productColors: "Silver, Black",
    productDimensions: "24x20x15 cm",
    productMaterial: "Stainless Steel",
    productWarrantyInfo: "1 Year Warranty",
    productReturnPolicy: "7-Day return policy",
    coverImageUrl: [],
  },
  {
    productCategoryId: "1",
    productName: "Non-Stick Frying Pan - 28cm",
    productDescription:
      "Durable and PFOA-free frying pan, ideal for everyday cooking.",
    productBrand: "CookMate",
    stockKeepingUnit: "CM-NSFP-28",
    productModelNumber: "NSFP-28",
    productBestSaleTag: "Hot Deal",
    productDiscountPercentage: 15,
    productPrice: 999,
    productDiscountPrice: 849,
    saleDayleft: 10,
    availableStockQuantity: 60,
    productWeight: 1.2,
    productSizes: "28cm",
    productColors: "Black",
    productDimensions: "28x5 cm",
    productMaterial: "Aluminium",
    productWarrantyInfo: "6 Months",
    productReturnPolicy: "Return within 5 days",
    coverImageUrl: [],
  },
  {
    productCategoryId: "1",
    productName: "Air Fryer 4L - Digital Touch",
    productDescription:
      "Oil-free cooking with smart temperature control and auto timer.",
    productBrand: "AirChef",
    stockKeepingUnit: "ACF-4000",
    productModelNumber: "AF-4000D",
    productBestSaleTag: "Top Rated",
    productDiscountPercentage: 25,
    productPrice: 5999,
    productDiscountPrice: 4499,
    saleDayleft: 30,
    availableStockQuantity: 80,
    productWeight: 4.0,
    productSizes: "4L",
    productColors: "Black",
    productDimensions: "30x28x35 cm",
    productMaterial: "ABS + Steel",
    productWarrantyInfo: "1 Year Replacement Warranty",
    productReturnPolicy: "10-Day Return Policy",
    coverImageUrl: [],
  },
  {
    productCategoryId: "1",
    productName: "12-Piece Stainless Steel Cutlery Set",
    productDescription:
      "Elegant dinnerware set for 6 people with mirror finish.",
    productBrand: "DineWell",
    stockKeepingUnit: "DW-CTLRY12",
    productModelNumber: "SS12DW",
    productBestSaleTag: "Bestseller",
    productDiscountPercentage: 10,
    productPrice: 1299,
    productDiscountPrice: 1169,
    saleDayleft: 7,
    availableStockQuantity: 200,
    productWeight: 1.0,
    productVideoUrl: "",
    productSizes: "",
    productColors: "Silver",
    productDimensions: "Box 25x18x5 cm",
    productMaterial: "Stainless Steel",
    productWarrantyInfo: "No Warranty",
    productReturnPolicy: "Return within 3 days",
    coverImageUrl: [],
  },
  {
    productCategoryId: "1",
    productName: "2-Slice Pop-Up Toaster",
    productDescription:
      "Browning control with removable crumb tray and cool-touch body.",
    productBrand: "ToastPro",
    stockKeepingUnit: "TP-2SLICE",
    productModelNumber: "TP200",
    productBestSaleTag: "Value Pick",
    productDiscountPercentage: 12,
    productPrice: 1499,
    productDiscountPrice: 1319,
    saleDayleft: 20,
    availableStockQuantity: 90,
    productWeight: 1.5,
    productSizes: "",
    productColors: "White",
    productDimensions: "26x16x18 cm",
    productMaterial: "Plastic + Steel",
    productWarrantyInfo: "2 Year Limited Warranty",
    productReturnPolicy: "7-Day Return Policy",
    coverImageUrl: [],
  },
];
